create table public.guild_settings (
    guild_id bigint primary key,
    notify_channel_id bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.watch_words (
    id bigint generated by default as identity primary key,
    guild_id bigint not null,
    word text not null,
    notify_enabled boolean not null default true,
    created_by bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint watch_words_guild_id_word_key unique (guild_id, word)
);

create table public.detections (
    id bigint generated by default as identity primary key,
    guild_id bigint not null,
    word_id bigint not null references public.watch_words (id) on delete cascade,
    word text not null,
    user_id bigint not null,
    channel_id bigint not null,
    message_id bigint not null,
    detected_at timestamptz not null default now()
);

create index watch_words_guild_id_idx
    on public.watch_words (guild_id);

create index detections_guild_word_detected_at_idx
    on public.detections (guild_id, word_id, detected_at);

create index detections_guild_detected_at_idx
    on public.detections (guild_id, detected_at);

alter table public.guild_settings enable row level security;
alter table public.watch_words enable row level security;
alter table public.detections enable row level security;

revoke all on table public.guild_settings from anon, authenticated;
revoke all on table public.watch_words from anon, authenticated;
revoke all on table public.detections from anon, authenticated;
